[WIP] Playing audio onscan events
jmcanterafonseca-iota/zebra-iota-edge-sdk pull request #104
Opened 2021-12-13 17:46 UTC by jmcanterafonseca-iota

2021-12-14 13:35 UTC, jmcanterafonseca-iota commented
#75

2021-12-14 15:35 UTC, 7opf requested changes
Works fine, but some changes needed and other suggested.

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/verifier-mobile-app/src/App.svelte
> +    import { playAudio, showAlert } from './lib/ui/helpers';
Unused import
```suggestion
    import { showAlert } from './lib/ui/helpers';
```

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/verifier-mobile-app/src/pages/InvalidCredential.svelte
> +        // We wait a little bit in order not to overlap the different aural feedback
typo :)
```suggestion
        // We wait a little bit in order not to overlap the different sounds
```

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/deviceId-mobile-app/src/lib/ui/helpers.ts
> +export async function playAudio(sound: string) {
I think we should extend this function to support a millisecond delay (default=0) as a second parameter so we don't repeat this everywhere

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/holder-mobile-app/src/lib/ui/helpers.ts
> +export async function playAudio(sound: string) {
Same comment regarding delay

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/verifier-mobile-app/src/lib/ui/helpers.ts
> +export async function playAudio(sound: string) {
Same comment regarding delay

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/deviceId-mobile-app/src/pages/Scan.svelte
> +                await playAudio('invalid');
Missing delay?

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/deviceId-mobile-app/src/pages/Scan.svelte
> +                await playAudio('invalid');
Missing delay?

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/deviceId-mobile-app/src/pages/Scan.svelte
> +                await playAudio('valid');
Missing delay?

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/deviceId-mobile-app/src/pages/Scan.svelte
> +            await playAudio('invalid');
Missing delay?

2021-12-14 15:35 UTC, 7opf commented on identity-enabler/verifier-mobile-app/src/lib/scan.ts
> +        playAudio('valid');
Missing delay?

2021-12-15 08:00 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/lib/scan.ts
> +        playAudio('valid');
not necessary as there is enough delay when processing a legit credential ...

2021-12-15 08:02 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/App.svelte
> +    import { playAudio, showAlert } from './lib/ui/helpers';
good catch

2021-12-15 08:25 UTC, merged