Scan enhancements
jmcanterafonseca-iota/zebra-iota-edge-sdk pull request #41
Opened 2021-11-29 16:00 UTC by 7opf

Addresses

- https://github.com/jmcanterafonseca-iota/zebra-iota-edge-sdk/issues/33
- https://github.com/jmcanterafonseca-iota/zebra-iota-edge-sdk/issues/40
- https://github.com/jmcanterafonseca-iota/zebra-iota-edge-sdk/issues/37

2021-11-29 17:34 UTC, jmcanterafonseca-iota requested changes
we need to improve onScan behaviour and also check why the Camera Preview is not appearing on Android devices.

2021-11-29 17:34 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/App.svelte
> +			try {
once we receive an scan we should inform the user so that we provide a hint we are processing it
Probably something to check with UX

2021-11-29 17:34 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/App.svelte
> +		window.onScan = async (scannedCodeStr) => {
this code block deserves a separate source file or a separate function

2021-11-29 17:34 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/App.svelte
> +					await updateStorage('credentials', { [vp.verifiableCredential.type[1].split(/\b/)[0].toLowerCase()]: vp.verifiableCredential });
very dangerous, are you assuming type[1] will always be defined?

2021-11-29 17:34 UTC, jmcanterafonseca-iota commented on identity-enabler/deviceId-mobile-app/src/pages/Scan.svelte
> +                    console.log("result", result.getText());
not needed

2021-11-29 17:34 UTC, jmcanterafonseca-iota commented on identity-enabler/deviceId-mobile-app/src/pages/Scan.svelte
> +                    handleScannerData({ detail: result.getText() });
can the scanner just accept an image stream instead of data URL which is very inefficient?

2021-11-29 17:34 UTC, jmcanterafonseca-iota commented on identity-enabler/deviceId-mobile-app/src/components/Scanner.svelte
> +        height: auto;
we need to check this CSS settings probably causing issues rendering the Camera Preview

2021-11-30 16:21 UTC, 7opf commented on identity-enabler/deviceId-mobile-app/src/pages/Scan.svelte
> +                    handleScannerData({ detail: result.getText() });
No, but I now use decodeFromImageUrl so a dummy img element doesn't need to be created.

2021-11-30 16:23 UTC, 7opf commented on identity-enabler/deviceId-mobile-app/src/components/Scanner.svelte
> +        height: auto;
Could be unsupported. See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#browser_compatibility

2021-11-30 16:24 UTC, 7opf commented on identity-enabler/verifier-mobile-app/src/App.svelte
> +					await updateStorage('credentials', { [vp.verifiableCredential.type[1].split(/\b/)[0].toLowerCase()]: vp.verifiableCredential });
This is the assumption in the codebase, yes. I have rewritten in latest commit to take the last element if one exists.

2021-11-30 16:25 UTC, 7opf commented on identity-enabler/verifier-mobile-app/src/App.svelte
> +		window.onScan = async (scannedCodeStr) => {
Verifier app has been significantly refactored in latest commit. This functionality was moved to function in lib/scan.ts

2021-12-06 12:20 UTC, 7opf commented on identity-enabler/verifier-mobile-app/src/App.svelte
> +			try {
Current implementation will display the loading screen.

2021-12-07 08:04 UTC, jmcanterafonseca-iota requested changes
some changes are needed, I would suggest not to change UX designs until we have input from them

2021-12-07 08:04 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/pages/Home.svelte
> +			position: 'center',
why are you adding this change without UX input?

I would suggest we stick to the UX designs

2021-12-07 08:04 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/pages/InvalidCredential.svelte
> +    const error = history.state.error as { message: string, detail?: string };
please define type

2021-12-07 12:35 UTC, jmcanterafonseca-iota requested changes
still changes needed, some content not needed found such as history

2021-12-07 12:35 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/lib/stores/LoaderScreenStore.ts
> + }
new line needed

2021-12-07 12:35 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/lib/stores/LoaderScreenStore.ts
> +    }
we do not use bind in TypeScript

2021-12-07 12:35 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/lib/stores/ScanStore.ts
> +    this.update = update.bind(this);
bind ...

2021-12-07 12:35 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/pages/ScanInfo.svelte
> +	import type { ScanSvelteStore } from "../lib/stores/ScanStore";
indentation

2021-12-07 12:36 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/lib/init.ts
> +	ServiceFactory.register('scans', () => new ScanSvelteStore('scans'));
indentation

2021-12-07 12:37 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/models/types/IInternalCredentialDataModel.ts
> +  enrichment: VerifiableCredentialEnrichment | null;
we don't use null in TypeScript

2021-12-07 12:38 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/src/pages/ScanInfo.svelte
> +        display: flex;
indentation broken

2021-12-09 14:41 UTC, jmcanterafonseca-iota commented
closed as already landed at other places

2021-12-09 14:41 UTC, closed without merging