lock mobile portrait mode
jmcanterafonseca-iota/zebra-iota-edge-sdk pull request #44
Opened 2021-12-01 08:51 UTC by 7opf

2021-12-01 12:34 UTC, jmcanterafonseca-iota requested changes

2021-12-01 12:34 UTC, jmcanterafonseca-iota commented on identity-enabler/verifier-mobile-app/android/app/src/main/java/com/hello/svelte/MainActivity.java
> +package org.iota.zebra;
be careful this class does no longer exist

2021-12-01 13:06 UTC, jmcanterafonseca-iota commented
this Pull Request has to be rebased

2021-12-07 07:38 UTC, jmcanterafonseca-iota commented
@7opf the verifier application is missing

2021-12-07 08:16 UTC, 7opf commented
> @7opf the verifier application is missing

@jmcanterafonseca-iota it's already configured: https://github.com/jmcanterafonseca-iota/zebra-iota-edge-sdk/blob/lock_rotation/identity-enabler/verifier-mobile-app/android/app/src/main/java/org/iota/zebra/verifier/MainActivity.java

2021-12-09 08:08 UTC, merged